;策略组定义
custom_proxy_group=🐟 漏网之鱼`select`[]DIRECT`[]REJECT`[]🛩️ 手机`[]♻️ 自动选择`[]🏡 房间`.*`

;独立设备组（排序：直连 > 拦截 > 自动选择 > 节点）
custom_proxy_group=🛩️ 手机`select`[]DIRECT`[]REJECT`[]♻️ 自动选择`.*`
custom_proxy_group=🏡 房间`select`[]DIRECT`[]♻️ 自动选择`.*`
custom_proxy_group=🇭🇰 客厅电脑`select`[]DIRECT`[]REJECT`[]♻️ 自动选择`.*`
custom_proxy_group=电视`select`[]DIRECT`[]REJECT`[]♻️ 自动选择`.*`
custom_proxy_group=妈妈和彩萍`select`[]DIRECT`[]REJECT`[]♻️ 自动选择`.*`
custom_proxy_group=国外`select`[]DIRECT`[]REJECT`[]♻️ 自动选择`.*`
custom_proxy_group=国内`select`[]DIRECT`[]REJECT`[]♻️ 自动选择`.*`

;自动测速组
custom_proxy_group=♻️ 自动选择`url-test`.*`http://www.gstatic.com/generate_204`300,,2

;启用自定义规则集
enable_rule_generator=true
overwrite_original_rules=true

;规则集定义
ruleset=🐟 漏网之鱼,[]FINAL
